// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZfwJQYBmclysUFOKVNb1no9qMd7hqmM',
    appId: '1:688131321583:web:8d1af5ffd11df3995db51a',
    messagingSenderId: '688131321583',
    projectId: 'authentication-b02f7',
    authDomain: 'authentication-b02f7.firebaseapp.com',
    storageBucket: 'authentication-b02f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_L3r6riLiMbRI-7jy0sHOztkxEH5KEk8',
    appId: '1:688131321583:android:a7468983642741185db51a',
    messagingSenderId: '688131321583',
    projectId: 'authentication-b02f7',
    storageBucket: 'authentication-b02f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Me_jcw_OA9sc40Ylyxt2uCESHdiabnc',
    appId: '1:688131321583:ios:9d857f83c1aeef1f5db51a',
    messagingSenderId: '688131321583',
    projectId: 'authentication-b02f7',
    storageBucket: 'authentication-b02f7.appspot.com',
    androidClientId: '688131321583-qk9lbh262cj793f01q2gubgpgbtimqlu.apps.googleusercontent.com',
    iosClientId: '688131321583-efdvcipf8v04qk5b0m4mqp0d3v9bqh1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Me_jcw_OA9sc40Ylyxt2uCESHdiabnc',
    appId: '1:688131321583:ios:9d857f83c1aeef1f5db51a',
    messagingSenderId: '688131321583',
    projectId: 'authentication-b02f7',
    storageBucket: 'authentication-b02f7.appspot.com',
    androidClientId: '688131321583-qk9lbh262cj793f01q2gubgpgbtimqlu.apps.googleusercontent.com',
    iosClientId: '688131321583-efdvcipf8v04qk5b0m4mqp0d3v9bqh1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus',
  );
}
